export default resList = [
  {
    info: {
      id: "375041",
      name: "Andhra Gunpowder",
      cloudinaryImageId: "byilgyrcfz690ryoasww",
      locality: "6th Block",
      areaName: "Koramangala",
      costForTwo: "₹350 for two",
      cuisines: ["Andhra", "Biryani", "South Indian"],
      avgRating: 4.4,
      deliveryTime: 16,
    },
  },
  {
    info: {
      id: "25620",
      name: "KFC",
      cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
      locality: "Intermediate Ring Road",
      areaName: "Ejipura",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRating: 4.2,
      deliveryTime: 17,
    },
  },
  {
    info: {
      id: "65797",
      name: "Leon's - Burgers & Wings (Leon Grill)",
      cloudinaryImageId: "b2edbc28b7b8219d6e0a9c049ce06658",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹300 for two",
      cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
      avgRating: 4.4,
      deliveryTime: 20,
    },
  },
  {
    info: {
      id: "18973",
      name: "Nandhana Palace",
      cloudinaryImageId: "195876a3181ef63f76e45e3a7b49b585",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Andhra", "South Indian", "North Indian"],
      avgRating: 4.2,
      deliveryTime: 16,
    },
  },
  {
    info: {
      id: "38634",
      name: "Third Wave Coffee",
      cloudinaryImageId: "d96267738c19ec62acb5390e52faba41",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹400 for two",
      cuisines: ["Beverages", "Bakery", "Continental"],
      avgRating: 4.5,
      deliveryTime: 23,
    },
  },
  {
    info: {
      id: "50467",
      name: "Bakingo",
      cloudinaryImageId: "0c53fd8f62e3d25ba56d1b4cfe572cef",
      locality: "1st Block",
      areaName: "Koramangala",
      costForTwo: "₹300 for two",
      cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
      avgRating: 4.3,
      deliveryTime: 20,
    },
  },
  {
    info: {
      id: "140887",
      name: "McDonald's",
      cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
      locality: "Mantri Avenue",
      areaName: "Koramangala",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.5,
      deliveryTime: 17,
    },
  },
  {
    info: {
      id: "5934",
      name: "Burger King",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.3,
      deliveryTime: 25,
    },
  },
  {
    info: {
      id: "108424",
      name: "Domino's Pizza",
      cloudinaryImageId: "vw6n5betlssnqelt7rmu",
      locality: "5TH Block",
      areaName: "Koramangala",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRating: 4.4,
      deliveryTime: 25,
    },
  },
  {
    info: {
      id: "10820",
      name: "California Burrito",
      cloudinaryImageId: "b58sysfvskincfwmgoqd",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹250 for two",
      cuisines: [
        "Mexican",
        "American",
        "Salads",
        "Continental",
        "Keto",
        "Healthy Food",
      ],
      avgRating: 4.6,
      deliveryTime: 18,
    },
  },
  {
    info: {
      id: "158855",
      name: "Candice's Gourmet Sandwiches & Wraps",
      cloudinaryImageId: "d1331113564b015c9d55c48ff48a2553",
      locality: "5th Block",
      areaName: "Koramangala",
      costForTwo: "₹600 for two",
      cuisines: [
        "Continental",
        "American",
        "Salads",
        "Desserts",
        "Beverages",
        "Healthy Food",
      ],
      avgRating: 4.6,
      deliveryTime: 26,
    },
  },
  {
    info: {
      id: "425",
      name: "Hotel Empire",
      cloudinaryImageId: "un4omn7rcunkmlw6vikr",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹450 for two",
      cuisines: ["North Indian", "Kebabs", "Biryani"],
      avgRating: 4.3,
      deliveryTime: 27,
    },
  },
  {
    info: {
      id: "381853",
      name: "ITC Master Chef Creations",
      cloudinaryImageId: "b15a2367ff3d6f0bf92d1def3c1e5c59",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹650 for two",
      cuisines: ["North Indian", "Biryani", "Indian", "Desserts", "Snacks"],
      avgRating: 4.5,
      deliveryTime: 29,
    },
  },
  {
    info: {
      id: "209557",
      name: "Subway",
      cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
      locality: "JNC College Road",
      areaName: "Koramangala",
      costForTwo: "₹350 for two",
      cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
      avgRating: 4.3,
      deliveryTime: 24,
    },
  },
  {
    info: {
      id: "19563",
      name: "The Bowl Company",
      cloudinaryImageId: "bb6049fae59b8a2413a9177eb0338b49",
      locality: "Jakkasandra",
      areaName: "Koramangala",
      costForTwo: "₹300 for two",
      cuisines: [
        "Pan-Asian",
        "Continental",
        "North Indian",
        "Desserts",
        "American",
        "Asian",
        "European",
        "Grill",
      ],
      avgRating: 4.4,
      deliveryTime: 20,
    },
  },
  {
    info: {
      id: "305",
      name: "A2B - Adyar Ananda Bhavan",
      cloudinaryImageId: "gxydb9wvkadarapno4hk",
      locality: "7th Block",
      areaName: "Koramangala",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "North Indian", "Sweets", "Chinese"],
      avgRating: 4.3,
      deliveryTime: 27,
    },
  },
  {
    info: {
      id: "272239",
      name: "EatFit",
      cloudinaryImageId: "6126c9b45de2cb222405c1af8a321e74",
      locality: "6th Block",
      areaName: "Koramangala",
      costForTwo: "₹270 for two",
      cuisines: [
        "Chinese",
        "Healthy Food",
        "Tandoor",
        "Pizzas",
        "North Indian",
        "Thalis",
        "Biryani",
      ],
      avgRating: 4.5,
      deliveryTime: 16,
    },
  },
  {
    info: {
      id: "156119",
      name: "The Good Bowl",
      cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
      locality: "Jakkasandra",
      areaName: "Hsr Layout 5th Sector",
      costForTwo: "₹400 for two",
      cuisines: [
        "Biryani",
        "North Indian",
        "Pastas",
        "Punjabi",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.2,
      deliveryTime: 25,
    },
  },
];
